# -*- coding: utf-8 -*-
"""skim_attention_titml_2mix_raw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ng-RkV46kpAD5TfBIGzuZv0eCqLWxUS

# Train SkiMAttention Model from Scratch for Indonesian Speech Separation

**Goal**: Build and train SkiMAttention (Skipping Memory with Multi-Head Self-Attention) model from random initialization on TITML-IDN-mix dataset

**Dataset**:
- Train: 3000 mixtures (~3.3 hours)
- Dev: 500 mixtures (~33 minutes)
- Test: 500 mixtures (~33 minutes)
- Format: 16kHz, 2-speaker separation, 4s duration
- Language: Bahasa Indonesia

**Model**: SkiMAttention - Small Causal variant
- Architecture: Conv Encoder → SkiMAttention Separator (3 layers, 512 units, 8 heads) → Conv Decoder
- Key difference from SkiM: Mem-LSTM replaced by Multi-Head Self-Attention + FFN
- Initialization: Random (no pre-trained weights)
- Loss: SI-SNR with Permutation Invariant Training (PIT)

**Platform**: Google Colab (Free GPU/TPU)

**Differences from original SkiM**:
- ✅ MemLSTM replaced by MemAttention (Multi-Head Self-Attention + FFN + LayerNorm)
- ✅ num_heads=8 (attention heads per MemAttention block)
- ✅ Same SegLSTM, same encoder/decoder, same training setup
- ✅ Slightly higher parameter count due to attention projection matrices

## 1. Environment Setup
"""

# Check GPU availability
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
else:
    print("⚠️ No GPU detected! Training will be slow on CPU.")

# Install ESPnet and dependencies
!pip install -q espnet==202304
!pip install -q espnet_model_zoo
!pip install -q soundfile librosa pesq pystoi mir_eval
print("✓ Installation complete!")

# Mount Google Drive (dataset + implementation files stored there)
from google.colab import drive
drive.mount('/content/drive')

# Import required libraries
import json
import numpy as np
import soundfile as sf
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings('ignore')
import os

print("✓ Libraries imported successfully")

"""## 2. Dataset Configuration"""

# Dataset path configuration
# ⚠️ UPDATE THIS PATH based on where you upload your dataset in Colab
DATASET_BASE = "/content/drive/MyDrive/Tugas Akhir/Dataset/IndonesianMix/"

TRAIN_DIR = os.path.join(DATASET_BASE, "train")
DEV_DIR = os.path.join(DATASET_BASE, "dev")
TEST_DIR = os.path.join(DATASET_BASE, "test")

# Verify dataset exists
if os.path.exists(DATASET_BASE):
    print(f"✓ Dataset found at: {DATASET_BASE}")
    print(f"  - Train: {os.path.exists(TRAIN_DIR)}")
    print(f"  - Dev:   {os.path.exists(DEV_DIR)}")
    print(f"  - Test:  {os.path.exists(TEST_DIR)}")
else:
    print(f"⚠️ Dataset not found at: {DATASET_BASE}")
    print("Please update DATASET_BASE path or upload the dataset!")

# Custom Dataset class for IndonesianMix
class IndonesianMixDataset(Dataset):
    """
    Dataset for TITML-IDN-mix Indonesian speech separation

    Structure:
    - mix/: mixed audio files
    - s1/: source 1 (speaker 1)
    - s2/: source 2 (speaker 2)
    - metadata.json: dataset metadata
    """

    def __init__(self, data_dir, split='train', sample_rate=16000, max_length=64000):
        self.data_dir = Path(data_dir)
        self.split = split
        self.sample_rate = sample_rate
        self.max_length = max_length  # Fixed length (4 seconds at 16kHz)

        # Load metadata
        metadata_path = self.data_dir / 'metadata.json'
        with open(metadata_path, 'r') as f:
            self.metadata = json.load(f)

        # Get file list
        mix_dir = self.data_dir / 'mix'
        self.file_list = sorted([f.stem for f in mix_dir.glob('*.wav')])

        print(f"Loaded {split} split: {len(self.file_list)} samples")
        print(f"Fixed length: {max_length} samples ({max_length/sample_rate:.1f}s)")

    def __len__(self):
        return len(self.file_list)

    def _pad_or_truncate(self, audio):
        """Pad or truncate audio to fixed length"""
        if len(audio) > self.max_length:
            audio = audio[:self.max_length]
        elif len(audio) < self.max_length:
            padding = self.max_length - len(audio)
            audio = np.pad(audio, (0, padding), mode='constant')
        return audio

    def __getitem__(self, idx):
        file_id = self.file_list[idx]

        mix_path = self.data_dir / 'mix' / f'{file_id}.wav'
        s1_path  = self.data_dir / 's1'  / f'{file_id}.wav'
        s2_path  = self.data_dir / 's2'  / f'{file_id}.wav'

        mix, sr_mix = sf.read(mix_path)
        s1,  sr_s1  = sf.read(s1_path)
        s2,  sr_s2  = sf.read(s2_path)

        assert sr_mix == self.sample_rate, f"Expected {self.sample_rate}Hz, got {sr_mix}Hz"

        mix = self._pad_or_truncate(mix)
        s1  = self._pad_or_truncate(s1)
        s2  = self._pad_or_truncate(s2)

        return {
            'mix': torch.FloatTensor(mix),
            's1':  torch.FloatTensor(s1),
            's2':  torch.FloatTensor(s2),
            'file_id': file_id
        }

print("✓ Dataset class defined")

# Create datasets and dataloaders
BATCH_SIZE  = 4  # Adjust based on GPU memory (4-8 for Colab)
NUM_WORKERS = 0  # Set to 0 for Colab stability

train_dataset = IndonesianMixDataset(TRAIN_DIR, split='train')
dev_dataset   = IndonesianMixDataset(DEV_DIR,   split='dev')
test_dataset  = IndonesianMixDataset(TEST_DIR,  split='test')

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=NUM_WORKERS, pin_memory=True)
dev_loader   = DataLoader(dev_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)

print(f"\n✓ DataLoaders created:")
print(f"  - Train batches: {len(train_loader)} (batch_size={BATCH_SIZE})")
print(f"  - Dev batches:   {len(dev_loader)}")
print(f"  - Test batches:  {len(test_loader)}")

# Verify data loading with a sample batch
sample_batch = next(iter(train_loader))
print(f"\n✓ Sample batch loaded:")
print(f"  - Mix shape: {sample_batch['mix'].shape}")
print(f"  - S1 shape:  {sample_batch['s1'].shape}")
print(f"  - S2 shape:  {sample_batch['s2'].shape}")
print(f"  - File IDs:  {sample_batch['file_id'][:2]}")

"""## 3. Build SkiMAttention Model from Scratch"""

# Import ESPnet components
from espnet2.enh.encoder.conv_encoder import ConvEncoder
from espnet2.enh.decoder.conv_decoder import ConvDecoder
from espnet2.enh.espnet_model import ESPnetEnhancementModel
from espnet2.enh.loss.criterions.time_domain import SISNRLoss
from espnet2.enh.loss.wrappers.pit_solver import PITSolver

print("✓ ESPnet components imported")

# ── SkiMAttention core architecture (inline — no file copy needed) ──────────
import torch
import torch.nn as nn
from espnet2.enh.layers.dprnn import SingleRNN, merge_feature, split_feature
from espnet2.enh.layers.tcn import choose_norm


class MemAttention(nn.Module):
    """Multi-Head Self-Attention replacing Mem-LSTM in SkiM."""

    def __init__(self, hidden_size, num_heads=4, dropout=0.0, mem_type="hc", norm_type="cLN"):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_heads   = num_heads
        self.mem_type    = mem_type
        self.norm_type   = norm_type

        assert mem_type in ["hc", "h", "c", "id"], \
            f"only support 'hc', 'h', 'c' and 'id', got: {mem_type}"
        assert hidden_size % num_heads == 0, \
            f"hidden_size ({hidden_size}) must be divisible by num_heads ({num_heads})"

        if mem_type in ["hc", "h"]:
            self.h_attn  = nn.MultiheadAttention(hidden_size, num_heads, dropout=dropout, batch_first=True)
            self.h_ffn   = nn.Sequential(
                nn.Linear(hidden_size, hidden_size * 4), nn.ReLU(), nn.Dropout(dropout),
                nn.Linear(hidden_size * 4, hidden_size), nn.Dropout(dropout),
            )
            self.h_norm1 = nn.LayerNorm(hidden_size)
            self.h_norm2 = nn.LayerNorm(hidden_size)

        if mem_type in ["hc", "c"]:
            self.c_attn  = nn.MultiheadAttention(hidden_size, num_heads, dropout=dropout, batch_first=True)
            self.c_ffn   = nn.Sequential(
                nn.Linear(hidden_size, hidden_size * 4), nn.ReLU(), nn.Dropout(dropout),
                nn.Linear(hidden_size * 4, hidden_size), nn.Dropout(dropout),
            )
            self.c_norm1 = nn.LayerNorm(hidden_size)
            self.c_norm2 = nn.LayerNorm(hidden_size)

    def extra_repr(self):
        return f"mem_type={self.mem_type}, num_heads={self.num_heads}"

    def forward(self, hc, S, causal=False):
        if self.mem_type == "id":
            return hc

        h, c = hc
        d, BS, H = h.shape
        B = BS // S

        h = h.transpose(1, 0).contiguous().view(B, S, d * H)
        c = c.transpose(1, 0).contiguous().view(B, S, d * H)

        attn_mask = None
        if causal:
            attn_mask = torch.triu(
                torch.full((S, S), float('-inf'), device=h.device), diagonal=1
            )

        if self.mem_type in ["hc", "h"]:
            h_out, _ = self.h_attn(h, h, h, attn_mask=attn_mask)
            h = self.h_norm1(h + h_out)
            h = self.h_norm2(h + self.h_ffn(h))
        if self.mem_type in ["hc", "c"]:
            c_out, _ = self.c_attn(c, c, c, attn_mask=attn_mask)
            c = self.c_norm1(c + c_out)
            c = self.c_norm2(c + self.c_ffn(c))
        if self.mem_type == "h":
            c = torch.zeros_like(c)
        if self.mem_type == "c":
            h = torch.zeros_like(h)

        h = h.view(B * S, d, H).transpose(1, 0).contiguous()
        c = c.view(B * S, d, H).transpose(1, 0).contiguous()
        return (h, c)

    def forward_one_step(self, hc, state, causal=True):
        if self.mem_type == "id":
            return hc, state
        h, c = hc
        d, B, H = h.shape
        h = h.transpose(1, 0).contiguous().view(B, 1, d * H)
        c = c.transpose(1, 0).contiguous().view(B, 1, d * H)
        if self.mem_type in ["hc", "h"]:
            h_out, _ = self.h_attn(h, h, h)
            h = self.h_norm1(h + h_out)
            h = self.h_norm2(h + self.h_ffn(h))
        if self.mem_type in ["hc", "c"]:
            c_out, _ = self.c_attn(c, c, c)
            c = self.c_norm1(c + c_out)
            c = self.c_norm2(c + self.c_ffn(c))
        if self.mem_type == "h":
            c = torch.zeros_like(c)
        if self.mem_type == "c":
            h = torch.zeros_like(h)
        h = h.transpose(1, 0).contiguous()
        c = c.transpose(1, 0).contiguous()
        return (h, c), state


class SegLSTM(nn.Module):
    """Seg-LSTM block of SkiM (unchanged from original)."""

    def __init__(self, input_size, hidden_size, dropout=0.0, bidirectional=False, norm_type="cLN"):
        super().__init__()
        self.input_size    = input_size
        self.hidden_size   = hidden_size
        self.num_direction = int(bidirectional) + 1
        self.lstm  = nn.LSTM(input_size, hidden_size, 1, batch_first=True, bidirectional=bidirectional)
        self.dropout = nn.Dropout(p=dropout)
        self.proj  = nn.Linear(hidden_size * self.num_direction, input_size)
        self.norm  = choose_norm(norm_type=norm_type, channel_size=input_size, shape="BTD")

    def forward(self, input, hc):
        B, T, H = input.shape
        if hc is None:
            d = self.num_direction
            h = torch.zeros(d, B, self.hidden_size, dtype=input.dtype, device=input.device)
            c = torch.zeros(d, B, self.hidden_size, dtype=input.dtype, device=input.device)
        else:
            h, c = hc
        output, (h, c) = self.lstm(input, (h, c))
        output = self.dropout(output)
        output = self.proj(output.contiguous().view(-1, output.shape[2])).view(input.shape)
        output = input + self.norm(output)
        return output, (h, c)


class SkiM(nn.Module):
    """SkiM with MemAttention (Multi-Head Self-Attention) replacing Mem-LSTM."""

    def __init__(
        self,
        input_size,
        hidden_size,
        output_size,
        dropout=0.0,
        num_blocks=2,
        segment_size=20,
        bidirectional=True,
        mem_type="hc",
        norm_type="gLN",
        seg_overlap=False,
        num_heads=4,
    ):
        super().__init__()
        self.input_size   = input_size
        self.output_size  = output_size
        self.hidden_size  = hidden_size
        self.segment_size = segment_size
        self.num_blocks   = num_blocks
        self.mem_type     = mem_type
        self.seg_overlap  = seg_overlap
        self.num_heads    = num_heads

        self.seg_lstms = nn.ModuleList([
            SegLSTM(input_size, hidden_size, dropout=dropout,
                    bidirectional=bidirectional, norm_type=norm_type)
            for _ in range(num_blocks)
        ])
        if mem_type is not None:
            self.mem_lstms = nn.ModuleList([
                MemAttention(hidden_size, num_heads=num_heads, dropout=dropout,
                             mem_type=mem_type, norm_type=norm_type)
                for _ in range(num_blocks - 1)
            ])
        self.output_fc = nn.Sequential(nn.PReLU(), nn.Conv1d(input_size, output_size, 1))

    def _padfeature(self, input):
        B, T, D = input.shape
        rest = self.segment_size - T % self.segment_size
        if rest > 0:
            input = torch.nn.functional.pad(input, (0, 0, 0, rest))
        return input, rest

    def forward(self, input):
        B, T, D = input.shape
        if self.seg_overlap:
            input, rest = split_feature(input.transpose(1, 2), segment_size=self.segment_size)
            input = input.permute(0, 3, 2, 1).contiguous()
        else:
            input, rest = self._padfeature(input)
            input = input.view(B, -1, self.segment_size, D)
        B, S, K, D = input.shape

        output = input.view(B * S, K, D).contiguous()
        hc = None
        for i in range(self.num_blocks):
            output, hc = self.seg_lstms[i](output, hc)
            if self.mem_type and i < self.num_blocks - 1:
                hc = self.mem_lstms[i](hc, S, causal=False)

        if self.seg_overlap:
            output = output.view(B, S, K, D).permute(0, 3, 2, 1)
            output = merge_feature(output, rest)
            output = self.output_fc(output).transpose(1, 2)
        else:
            output = output.view(B, S * K, D)[:, :T, :]
            output = self.output_fc(output.transpose(1, 2)).transpose(1, 2)
        return output

    def forward_stream(self, input_frame, states):
        B, _, N = input_frame.shape

        def empty_seg_states():
            shp = (1, B, self.hidden_size)
            return (
                torch.zeros(*shp, device=input_frame.device, dtype=input_frame.dtype),
                torch.zeros(*shp, device=input_frame.device, dtype=input_frame.dtype),
            )

        if not states:
            states = {
                "current_step": 0,
                "seg_state": [empty_seg_states() for _ in range(self.num_blocks)],
                "mem_state": [[None, None]        for _ in range(self.num_blocks - 1)],
            }

        output = input_frame
        if states["current_step"] and states["current_step"] % self.segment_size == 0:
            tmp_states = [empty_seg_states() for _ in range(self.num_blocks)]
            for i in range(self.num_blocks - 1):
                tmp_states[i + 1], states["mem_state"][i] = self.mem_lstms[i].forward_one_step(
                    states["seg_state"][i], states["mem_state"][i], causal=True
                )
            states["seg_state"] = tmp_states

        for i in range(self.num_blocks):
            output, states["seg_state"][i] = self.seg_lstms[i](output, states["seg_state"][i])

        states["current_step"] += 1
        output = self.output_fc(output.transpose(1, 2)).transpose(1, 2)
        return output, states


print("✓ MemAttention, SegLSTM, SkiM defined")

# ── SkiMAttentionSeparator (inline — uses SkiM defined above) ───────────────
from collections import OrderedDict
from typing import Dict, List, Optional, Tuple, Union

from torch_complex.tensor import ComplexTensor
from espnet2.enh.layers.complex_utils import is_complex
from espnet2.enh.separator.abs_separator import AbsSeparator


class SkiMAttentionSeparator(AbsSeparator):
    """SkiM Separator with MemAttention replacing Mem-LSTM.

    Args:
        input_dim:      input feature dimension (must match encoder channel)
        causal:         causal (online) mode
        num_spk:        number of target speakers
        predict_noise:  whether to output a noise estimate
        nonlinear:      mask activation — 'relu', 'tanh', or 'sigmoid'
        layer:          number of SkiM blocks
        unit:           hidden size of SegLSTM
        segment_size:   frames per segment for SegLSTM
        dropout:        dropout probability
        mem_type:       'hc', 'h', 'c', 'id' — which LSTM states MemAttention processes
        seg_overlap:    50% segment overlap (non-causal only)
        num_heads:      attention heads in MemAttention (must divide `unit`)
    """

    def __init__(
        self,
        input_dim: int,
        causal: bool = True,
        num_spk: int = 2,
        predict_noise: bool = False,
        nonlinear: str = "relu",
        layer: int = 3,
        unit: int = 512,
        segment_size: int = 20,
        dropout: float = 0.0,
        mem_type: str = "hc",
        seg_overlap: bool = False,
        num_heads: int = 4,
    ):
        super().__init__()
        self._num_spk       = num_spk
        self.predict_noise  = predict_noise
        self.segment_size   = segment_size

        if mem_type not in ("hc", "h", "c", "id", None):
            raise ValueError(f"Not supporting mem_type={mem_type}")

        self.num_outputs = self.num_spk + 1 if self.predict_noise else self.num_spk
        self.skim = SkiM(
            input_size=input_dim,
            hidden_size=unit,
            output_size=input_dim * self.num_outputs,
            dropout=dropout,
            num_blocks=layer,
            bidirectional=(not causal),
            norm_type="cLN" if causal else "gLN",
            segment_size=segment_size,
            seg_overlap=seg_overlap,
            mem_type=mem_type,
            num_heads=num_heads,
        )

        if nonlinear not in ("sigmoid", "relu", "tanh"):
            raise ValueError(f"Not supporting nonlinear={nonlinear}")
        self.nonlinear = {"sigmoid": nn.Sigmoid(), "relu": nn.ReLU(), "tanh": nn.Tanh()}[nonlinear]

    def forward(
        self,
        input: Union[torch.Tensor, ComplexTensor],
        ilens: torch.Tensor,
        additional: Optional[Dict] = None,
    ) -> Tuple[List[Union[torch.Tensor, ComplexTensor]], torch.Tensor, OrderedDict]:
        feature = abs(input) if is_complex(input) else input
        B, T, N = feature.shape

        processed = self.skim(feature)              # B, T, N*num_outputs
        processed = processed.view(B, T, N, self.num_outputs)
        masks = self.nonlinear(processed).unbind(dim=3)

        if self.predict_noise:
            *masks, mask_noise = masks

        masked = [input * m for m in masks]
        others = OrderedDict(
            zip([f"mask_spk{i+1}" for i in range(len(masks))], masks)
        )
        if self.predict_noise:
            others["noise1"] = input * mask_noise

        return masked, ilens, others

    def forward_streaming(self, input_frame: torch.Tensor, states=None):
        feature = abs(input_frame) if is_complex(input_frame) else input_frame
        B, _, N = feature.shape

        processed, states = self.skim.forward_stream(feature, states=states)
        processed = processed.view(B, 1, N, self.num_outputs)
        masks = self.nonlinear(processed).unbind(dim=3)

        if self.predict_noise:
            *masks, mask_noise = masks

        masked = [input_frame * m for m in masks]
        others = OrderedDict(
            zip([f"mask_spk{i+1}" for i in range(len(masks))], masks)
        )
        if self.predict_noise:
            others["noise1"] = input_frame * mask_noise

        return masked, states, others

    @property
    def num_spk(self):
        return self._num_spk


print("✓ SkiMAttentionSeparator defined")

# Model configuration - Small Causal variant with Multi-Head Self-Attention
model_config = {
    # Encoder/Decoder (TasNet-style for 16kHz) — identical to SkiM baseline
    'encoder': {
        'channel':     512,  # Number of filters (basis functions)
        'kernel_size': 32,   # 2ms window at 16kHz
        'stride':      16,   # 1ms hop (50% overlap)
    },
    'decoder': {
        'channel':     512,
        'kernel_size': 32,
        'stride':      16,
    },
    # SkiMAttention Separator - Small Causal
    'separator': {
        'input_dim':    512,   # Must match encoder channel
        'causal':       True,  # Causal (online) processing
        'num_spk':      2,     # 2 speakers
        'predict_noise': False,
        'nonlinear':    'relu',
        'layer':        3,     # 3 SkiMAttention blocks (Small variant)
        'unit':         512,   # Hidden LSTM dimension (SegLSTM)
        'segment_size': 20,    # Segment size for SegLSTM
        'dropout':      0.0,
        'mem_type':     'hc',  # Process both h and c through MemAttention
        'seg_overlap':  False, # No overlap for causal mode
        'num_heads':    8,     # Attention heads in MemAttention (512 / 8 = 64 per head)
    },
    'model': {
        'num_spk':   2,
        'loss_type': 'si_snr',
    }
}

print("✓ Model configuration:")
print(f"  - Architecture: Conv Encoder → SkiMAttention Separator → Conv Decoder")
print(f"  - Variant: Small-Causal (3 layers, 512 units)")
print(f"  - MemAttention: num_heads={model_config['separator']['num_heads']} "
      f"({model_config['separator']['unit'] // model_config['separator']['num_heads']} dims/head)")
print(f"  - Loss: SI-SNR with PIT")
print(f"  - Speakers: {model_config['separator']['num_spk']}")

# Build encoder
encoder = ConvEncoder(
    channel=model_config['encoder']['channel'],
    kernel_size=model_config['encoder']['kernel_size'],
    stride=model_config['encoder']['stride'],
)

print("✓ Encoder built:")
print(f"  - Type: Conv1D")
print(f"  - Channels: {model_config['encoder']['channel']}")
print(f"  - Kernel: {model_config['encoder']['kernel_size']} (stride={model_config['encoder']['stride']})")

# Build SkiMAttention separator
separator = SkiMAttentionSeparator(
    input_dim=model_config['separator']['input_dim'],
    causal=model_config['separator']['causal'],
    num_spk=model_config['separator']['num_spk'],
    predict_noise=model_config['separator']['predict_noise'],
    nonlinear=model_config['separator']['nonlinear'],
    layer=model_config['separator']['layer'],
    unit=model_config['separator']['unit'],
    segment_size=model_config['separator']['segment_size'],
    dropout=model_config['separator']['dropout'],
    mem_type=model_config['separator']['mem_type'],
    seg_overlap=model_config['separator']['seg_overlap'],
    num_heads=model_config['separator']['num_heads'],
)

print("✓ Separator built:")
print(f"  - Type: SkiMAttention (Multi-Head Self-Attention memory)")
print(f"  - Layers:       {model_config['separator']['layer']}")
print(f"  - Hidden units: {model_config['separator']['unit']}")
print(f"  - Segment size: {model_config['separator']['segment_size']}")
print(f"  - Num heads:    {model_config['separator']['num_heads']}")
print(f"  - Causal:       {model_config['separator']['causal']}")
print(f"  - Memory type:  {model_config['separator']['mem_type']}")

# Build decoder
decoder = ConvDecoder(
    channel=model_config['decoder']['channel'],
    kernel_size=model_config['decoder']['kernel_size'],
    stride=model_config['decoder']['stride'],
)

print("✓ Decoder built:")
print(f"  - Type: ConvTranspose1D")
print(f"  - Channels: {model_config['decoder']['channel']}")
print(f"  - Kernel: {model_config['decoder']['kernel_size']} (stride={model_config['decoder']['stride']})")

# Assemble full model with PIT + SI-SNR loss
si_snr_criterion = SISNRLoss()
pit_wrapper = PITSolver(criterion=si_snr_criterion)

model = ESPnetEnhancementModel(
    encoder=encoder,
    separator=separator,
    decoder=decoder,
    mask_module=None,
    loss_wrappers=[pit_wrapper],
    loss_type='si_snr',
)

print("\n✓ Complete model assembled:")
print(f"  - Pipeline: Encoder → SkiMAttention Separator → Decoder")
print(f"  - Loss: SI-SNR with PIT (Permutation Invariant Training)")
print(f"  - Initialization: Random weights (from scratch)")

total_params     = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nModel Parameters:")
print(f"  - Total:              {total_params:,}")
print(f"  - Trainable:          {trainable_params:,}")
print(f"  - Estimated GPU mem:  ~{total_params * 4 / 1e9:.2f} GB (float32)")

# Sanity check: single forward pass before training
device_check = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device_check)

with torch.no_grad():
    chk_batch = next(iter(train_loader))
    chk_mix = chk_batch['mix'].to(device_check)
    chk_s1  = chk_batch['s1'].to(device_check)
    chk_s2  = chk_batch['s2'].to(device_check)
    chk_len = torch.full((chk_mix.size(0),), chk_mix.size(1), dtype=torch.long, device=device_check)

    chk_loss, chk_stats, _ = model(
        speech_mix=chk_mix,
        speech_mix_lengths=chk_len,
        speech_ref1=chk_s1,
        speech_ref1_lengths=chk_len,
        speech_ref2=chk_s2,
        speech_ref2_lengths=chk_len,
    )

print(f"✓ Sanity check passed!")
print(f"  - Loss value: {chk_loss.item():.4f} (SI-SNR: {-chk_loss.item():.2f} dB)")
print(f"  - Loss is finite: {torch.isfinite(chk_loss).item()}")

"""## 4. Training Configuration"""

# Training hyperparameters
LEARNING_RATE   = 1e-3   # From-scratch learning rate
NUM_EPOCHS      = 20
GRADIENT_CLIP   = 5.0
PATIENCE        = 5
WEIGHT_DECAY    = 1e-5
CHECKPOINT_DIR  = "/content/drive/MyDrive/Tugas Akhir/checkpoints/skim_attention_mem/"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Device (already set during sanity check, reassign cleanly)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model  = model.to(device)
print(f"✓ Model on {device}")

# Optimizer
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE,
    betas=(0.9, 0.999),
    eps=1e-8,
    weight_decay=WEIGHT_DECAY
)

# LR scheduler
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=3
)

print(f"\nTraining Configuration:")
print(f"  - Learning Rate:   {LEARNING_RATE}")
print(f"  - Weight Decay:    {WEIGHT_DECAY}")
print(f"  - Max Epochs:      {NUM_EPOCHS}")
print(f"  - Batch Size:      {BATCH_SIZE}")
print(f"  - Gradient Clip:   {GRADIENT_CLIP}")
print(f"  - Early Stopping:  {PATIENCE} epochs")
print(f"  - LR Scheduler:    ReduceLROnPlateau (factor=0.5, patience=3)")
print(f"  - Checkpoint dir:  {CHECKPOINT_DIR}")

"""## 5. Training & Validation Functions"""

def train_epoch(model, train_loader, optimizer, device, epoch):
    model.train()
    total_loss = 0
    num_batches = len(train_loader)

    pbar = tqdm(train_loader, desc=f'Epoch {epoch} [Train]')
    for batch in pbar:
        mix = batch['mix'].to(device)
        s1  = batch['s1'].to(device)
        s2  = batch['s2'].to(device)

        batch_size  = mix.size(0)
        mix_lengths = torch.full((batch_size,), mix.size(1), dtype=torch.long, device=device)
        ref_lengths = mix_lengths.clone()

        loss, stats, weight = model(
            speech_mix=mix,
            speech_mix_lengths=mix_lengths,
            speech_ref1=s1,
            speech_ref1_lengths=ref_lengths,
            speech_ref2=s2,
            speech_ref2_lengths=ref_lengths,
        )

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRADIENT_CLIP)
        optimizer.step()

        total_loss += loss.item()
        avg_loss = total_loss / (pbar.n + 1)
        pbar.set_postfix({
            'loss':        f'{loss.item():.4f}',
            'SI-SNR':      f'{-loss.item():.2f}dB',
            'avg_SI-SNR':  f'{-avg_loss:.2f}dB',
        })

    return total_loss / num_batches

print("✓ Training function defined")

def validate(model, val_loader, device, epoch):
    model.eval()
    total_loss = 0
    num_batches = len(val_loader)

    with torch.no_grad():
        pbar = tqdm(val_loader, desc=f'Epoch {epoch} [Val]')
        for batch in pbar:
            mix = batch['mix'].to(device)
            s1  = batch['s1'].to(device)
            s2  = batch['s2'].to(device)

            batch_size  = mix.size(0)
            mix_lengths = torch.full((batch_size,), mix.size(1), dtype=torch.long, device=device)
            ref_lengths = mix_lengths.clone()

            loss, stats, weight = model(
                speech_mix=mix,
                speech_mix_lengths=mix_lengths,
                speech_ref1=s1,
                speech_ref1_lengths=ref_lengths,
                speech_ref2=s2,
                speech_ref2_lengths=ref_lengths,
            )

            total_loss += loss.item()
            pbar.set_postfix({'val_loss': f'{loss.item():.4f}'})

    return total_loss / num_batches

print("✓ Validation function defined")

"""## 6. Main Training Loop"""

best_val_loss   = float('inf')
patience_counter = 0
train_losses    = []
val_losses      = []

print("=" * 60)
print("Starting SkiMAttention Training from Scratch")
print("=" * 60)
print(f"Model:      SkiMAttention Small-Causal (3 layers, 512 units, 8 heads)")
print(f"Dataset:    TITML-IDN-mix (Indonesian, 16kHz)")
print(f"Train:      {len(train_dataset)} samples")
print(f"Validation: {len(dev_dataset)} samples")
print(f"Estimated:  ~{NUM_EPOCHS * len(train_loader) * 0.15 / 60:.1f} min ({NUM_EPOCHS} epochs)")
print("=" * 60)

for epoch in range(1, NUM_EPOCHS + 1):
    print(f"\nEpoch {epoch}/{NUM_EPOCHS}")
    print("-" * 60)

    train_loss = train_epoch(model, train_loader, optimizer, device, epoch)
    train_losses.append(train_loss)

    val_loss = validate(model, dev_loader, device, epoch)
    val_losses.append(val_loss)

    scheduler.step(val_loss)

    current_lr = optimizer.param_groups[0]['lr']
    print(f"\nEpoch {epoch} Summary:")
    print(f"  Train Loss: {train_loss:.4f}  (SI-SNR: {-train_loss:.2f} dB)")
    print(f"  Val Loss:   {val_loss:.4f}  (SI-SNR: {-val_loss:.2f} dB)")
    print(f"  LR:         {current_lr:.6f}")

    if val_loss < best_val_loss:
        best_val_loss    = val_loss
        patience_counter = 0

        ckpt_path = os.path.join(CHECKPOINT_DIR, 'best_model_attention.pth')
        torch.save({
            'epoch':             epoch,
            'model_state_dict':  model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss':        train_loss,
            'val_loss':          val_loss,
            'best_val_loss':     best_val_loss,
            'config':            model_config,
        }, ckpt_path)
        print(f"  ✓ Best model saved! (Val Loss: {val_loss:.4f})")
    else:
        patience_counter += 1
        print(f"  No improvement ({patience_counter}/{PATIENCE})")

    if patience_counter >= PATIENCE:
        print(f"\n⚠️ Early stopping triggered after {epoch} epochs")
        print(f"Best validation loss: {best_val_loss:.4f} (SI-SNR: {-best_val_loss:.2f} dB)")
        break

    if epoch % 10 == 0:
        ckpt_path = os.path.join(CHECKPOINT_DIR, f'checkpoint_epoch_{epoch}_attention.pth')
        torch.save({
            'epoch':            epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss':       train_loss,
            'val_loss':         val_loss,
        }, ckpt_path)
        print(f"  ✓ Checkpoint saved: checkpoint_epoch_{epoch}_attention.pth")

print("\n" + "=" * 60)
print("Training Complete!")
print("=" * 60)
print(f"Best validation SI-SNR: {-best_val_loss:.2f} dB")

# Plot training curves
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(train_losses, label='Train Loss', marker='o', markersize=3)
plt.plot(val_losses,   label='Val Loss',   marker='s', markersize=3)
plt.xlabel('Epoch')
plt.ylabel('Loss (Negative SI-SNR)')
plt.title('SkiMAttention Training and Validation Loss')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot([-l for l in train_losses], label='Train SI-SNR', marker='o', markersize=3)
plt.plot([-l for l in val_losses],   label='Val SI-SNR',   marker='s', markersize=3)
plt.xlabel('Epoch')
plt.ylabel('SI-SNR (dB)')
plt.title('SkiMAttention Training and Validation SI-SNR')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(CHECKPOINT_DIR, 'training_curves_attention.png'), dpi=150)
plt.show()

print(f"Best validation SI-SNR: {-best_val_loss:.2f} dB")

"""## 7. Evaluation on Test Set"""

# Load best model checkpoint for evaluation
checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, 'best_model_attention.pth'))
model.load_state_dict(checkpoint['model_state_dict'])
print(f"✓ Best model loaded (Epoch {checkpoint['epoch']}, Val Loss: {checkpoint['val_loss']:.4f})")

# Metric helper functions
def si_snr_loss(estimate, target, eps=1e-8):
    """SI-SNR as a loss (negative, for PIT permutation selection)"""
    estimate = estimate - estimate.mean(dim=-1, keepdim=True)
    target   = target   - target.mean(dim=-1,   keepdim=True)
    s_target = (torch.sum(estimate * target, dim=-1, keepdim=True) * target) / \
               (torch.sum(target ** 2, dim=-1, keepdim=True) + eps)
    e_noise  = estimate - s_target
    si_snr   = 10 * torch.log10(
        (torch.sum(s_target ** 2, dim=-1) + eps) /
        (torch.sum(e_noise  ** 2, dim=-1) + eps)
    )
    return -si_snr.mean()

def calculate_si_snr(estimate, target, eps=1e-8):
    """SI-SNR metric (positive dB value)"""
    estimate = estimate - estimate.mean(dim=-1, keepdim=True)
    target   = target   - target.mean(dim=-1,   keepdim=True)
    s_target = (torch.sum(estimate * target, dim=-1, keepdim=True) * target) / \
               (torch.sum(target ** 2, dim=-1, keepdim=True) + eps)
    e_noise  = estimate - s_target
    si_snr   = 10 * torch.log10(
        (torch.sum(s_target ** 2, dim=-1) + eps) /
        (torch.sum(e_noise  ** 2, dim=-1) + eps)
    )
    return si_snr

try:
    from mir_eval.separation import bss_eval_sources
    COMPUTE_SDR = True
    print("✓ mir_eval available — SDR will be computed")
except ImportError:
    print("⚠️ mir_eval not available, SDR will not be computed")
    COMPUTE_SDR = False

print("✓ Evaluation metric functions defined")

def evaluate_test_set(model, test_loader, device):
    model.eval()

    all_si_snr_mix     = []
    all_si_snr_est     = []
    all_si_snr_improve = []
    all_sdr_mix        = [] if COMPUTE_SDR else None
    all_sdr_est        = [] if COMPUTE_SDR else None

    with torch.no_grad():
        pbar = tqdm(test_loader, desc='Evaluating Test Set')
        for batch in pbar:
            mix = batch['mix'].to(device)
            s1  = batch['s1'].to(device)
            s2  = batch['s2'].to(device)

            targets     = torch.stack([s1, s2], dim=1)
            mix_lengths = torch.full((mix.size(0),), mix.size(1), dtype=torch.long, device=device)

            separated_output = model.forward_enhance(mix, mix_lengths)

            if isinstance(separated_output, (tuple, list)):
                estimates = separated_output[0]
            else:
                estimates = separated_output

            if isinstance(estimates, (list, tuple)):
                estimates = torch.stack(list(estimates), dim=1)

            while estimates.dim() > 3:
                estimates = estimates.squeeze(2)

            # PIT permutation selection
            perm_losses = []
            for perm in [(0, 1), (1, 0)]:
                loss = sum(si_snr_loss(estimates[:, i], targets[:, j]) for i, j in enumerate(perm))
                perm_losses.append(loss)
            best_perm = [(0, 1), (1, 0)][torch.argmin(torch.stack(perm_losses)).item()]

            for b in range(mix.size(0)):
                # SI-SNR of mixture (baseline)
                si_snr_mix = ((calculate_si_snr(mix[b:b+1], s1[b:b+1]) +
                               calculate_si_snr(mix[b:b+1], s2[b:b+1])) / 2)
                all_si_snr_mix.append(si_snr_mix.item())

                # SI-SNR of estimates
                est_s1 = estimates[b:b+1, best_perm[0]]
                est_s2 = estimates[b:b+1, best_perm[1]]
                si_snr_est = ((calculate_si_snr(est_s1, s1[b:b+1]) +
                               calculate_si_snr(est_s2, s2[b:b+1])) / 2)
                all_si_snr_est.append(si_snr_est.item())
                all_si_snr_improve.append((si_snr_est - si_snr_mix).item())

                if COMPUTE_SDR:
                    targets_np = torch.stack([s1[b], s2[b]]).cpu().numpy()
                    mix_np     = np.stack([mix[b].cpu().numpy(), mix[b].cpu().numpy()])
                    est_np     = torch.stack([est_s1[0], est_s2[0]]).cpu().numpy()
                    sdr_mix, _, _, _ = bss_eval_sources(targets_np, mix_np,  compute_permutation=False)
                    sdr_est, _, _, _ = bss_eval_sources(targets_np, est_np,  compute_permutation=False)
                    all_sdr_mix.append(sdr_mix.mean())
                    all_sdr_est.append(sdr_est.mean())

    results = {
        'SI-SNR_mix': np.mean(all_si_snr_mix),
        'SI-SNR_est': np.mean(all_si_snr_est),
        'SI-SNRi':    np.mean(all_si_snr_improve),
    }
    if COMPUTE_SDR:
        results['SDR_mix'] = np.mean(all_sdr_mix)
        results['SDR_est'] = np.mean(all_sdr_est)
        results['SDRi']    = np.mean(all_sdr_est) - np.mean(all_sdr_mix)

    return results


print("Evaluating on test set...")
test_results = evaluate_test_set(model, test_loader, device)

print("\n" + "=" * 60)
print("TEST SET RESULTS — SkiMAttention (From Scratch)")
print("=" * 60)
for metric, value in test_results.items():
    print(f"{metric:15s}: {value:7.2f} dB")
print("=" * 60)

"""## 8. Demo Visualization"""

import IPython.display as ipd

sample_idx  = np.random.randint(0, len(test_dataset))
sample      = test_dataset[sample_idx]

mix       = sample['mix'].unsqueeze(0).to(device)
s1_true   = sample['s1'].cpu().numpy()
s2_true   = sample['s2'].cpu().numpy()
file_id   = sample['file_id']
print(f"Sample: {file_id}")

model.eval()
with torch.no_grad():
    mix_lengths = torch.tensor([mix.size(1)], dtype=torch.long, device=device)
    separated_output = model.forward_enhance(mix, mix_lengths)

    if isinstance(separated_output, (tuple, list)):
        estimates = separated_output[0]
    else:
        estimates = separated_output

    if isinstance(estimates, (list, tuple)):
        estimates = torch.stack(list(estimates), dim=1)

    while estimates.dim() > 3:
        estimates = estimates.squeeze(2)

# Resolve permutation
s1_true_t = torch.FloatTensor(s1_true).unsqueeze(0).to(device)
s2_true_t = torch.FloatTensor(s2_true).unsqueeze(0).to(device)
perm1_loss = si_snr_loss(estimates[0:1, 0], s1_true_t) + si_snr_loss(estimates[0:1, 1], s2_true_t)
perm2_loss = si_snr_loss(estimates[0:1, 0], s2_true_t) + si_snr_loss(estimates[0:1, 1], s1_true_t)

if perm2_loss < perm1_loss:
    s1_est = estimates[0, 1].cpu().numpy()
    s2_est = estimates[0, 0].cpu().numpy()
    print("⚠️ Permutation swapped (normal — model does not know speaker identity)")
else:
    s1_est = estimates[0, 0].cpu().numpy()
    s2_est = estimates[0, 1].cpu().numpy()

mix_np = mix[0].cpu().numpy()

si_snr_s1 = calculate_si_snr(
    torch.FloatTensor(s1_est).unsqueeze(0),
    torch.FloatTensor(s1_true).unsqueeze(0)
).item()
si_snr_s2 = calculate_si_snr(
    torch.FloatTensor(s2_est).unsqueeze(0),
    torch.FloatTensor(s2_true).unsqueeze(0)
).item()

print(f"\nSeparation Quality:")
print(f"  SI-SNR Speaker 1: {si_snr_s1:.2f} dB")
print(f"  SI-SNR Speaker 2: {si_snr_s2:.2f} dB")
print(f"  Average SI-SNR:   {(si_snr_s1 + si_snr_s2) / 2:.2f} dB")

# Visualize waveforms
fig, axes = plt.subplots(5, 1, figsize=(15, 10))
time_axis = np.arange(len(mix_np)) / 16000

axes[0].plot(time_axis, mix_np,  color='black', linewidth=0.5)
axes[0].set_title('Mixed Audio (Input)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Amplitude')
axes[0].grid(True, alpha=0.3)

axes[1].plot(time_axis, s1_true, color='blue', linewidth=0.5)
axes[1].set_title('Speaker 1 — Ground Truth', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Amplitude')
axes[1].grid(True, alpha=0.3)

axes[2].plot(time_axis, s1_est,  color='cyan', linewidth=0.5)
axes[2].set_title(f'Speaker 1 — Estimated (SI-SNR: {si_snr_s1:.2f} dB)', fontsize=12, fontweight='bold')
axes[2].set_ylabel('Amplitude')
axes[2].grid(True, alpha=0.3)

axes[3].plot(time_axis, s2_true, color='red',    linewidth=0.5)
axes[3].set_title('Speaker 2 — Ground Truth', fontsize=12, fontweight='bold')
axes[3].set_ylabel('Amplitude')
axes[3].grid(True, alpha=0.3)

axes[4].plot(time_axis, s2_est,  color='orange', linewidth=0.5)
axes[4].set_title(f'Speaker 2 — Estimated (SI-SNR: {si_snr_s2:.2f} dB)', fontsize=12, fontweight='bold')
axes[4].set_ylabel('Amplitude')
axes[4].set_xlabel('Time (s)')
axes[4].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(CHECKPOINT_DIR, f'separation_demo_{file_id}_attention.png'), dpi=150)
plt.show()

# Audio playback (Colab)
print("Audio Playback:\n")

print("Mixed Audio:")
ipd.display(ipd.Audio(mix_np, rate=16000))

print("\nSpeaker 1 — Ground Truth:")
ipd.display(ipd.Audio(s1_true, rate=16000))
print("Speaker 1 — Estimated:")
ipd.display(ipd.Audio(s1_est,  rate=16000))

print("\nSpeaker 2 — Ground Truth:")
ipd.display(ipd.Audio(s2_true, rate=16000))
print("Speaker 2 — Estimated:")
ipd.display(ipd.Audio(s2_est,  rate=16000))

"""## 9. Save Final Model"""

final_model_path = os.path.join(CHECKPOINT_DIR, 'final_model_indonesian_skim_attention_raw.pth')

torch.save({
    'model_state_dict': model.state_dict(),
    'config':           model_config,
    'test_results':     test_results,
    'train_losses':     train_losses,
    'val_losses':       val_losses,
    'best_val_loss':    best_val_loss,
    'hyperparameters':  {
        'learning_rate':  LEARNING_RATE,
        'batch_size':     BATCH_SIZE,
        'num_epochs':     NUM_EPOCHS,
        'gradient_clip':  GRADIENT_CLIP,
        'weight_decay':   WEIGHT_DECAY,
        'patience':       PATIENCE,
        'training_type':  'from_scratch',
        'num_heads':      model_config['separator']['num_heads'],
    },
    'dataset_info': {
        'name':          'TITML-IDN-mix',
        'sample_rate':   16000,
        'train_samples': len(train_dataset),
        'dev_samples':   len(dev_dataset),
        'test_samples':  len(test_dataset),
    }
}, final_model_path)

print(f"✓ Final model saved to: {final_model_path}")
print(f"\nLoad with:")
print(f"  checkpoint = torch.load('{final_model_path}')")
print(f"  model.load_state_dict(checkpoint['model_state_dict'])")

"""---

## Summary

### Model Architecture
- **Encoder**: Conv1D (512 channels, kernel=32, stride=16)
- **Separator**: SkiMAttention (3 blocks, 512 hidden units, causal, segment_size=20)
  - **SegLSTM**: identical to original SkiM — processes each segment
  - **MemAttention**: replaces MemLSTM — Multi-Head Self-Attention (8 heads, 64 dims/head) + FFN (4× expansion) + LayerNorm on both *h* and *c* states
- **Decoder**: ConvTranspose1D (512 channels, kernel=32, stride=16)
- **Total Parameters**: ~17–18M (slightly more than SkiM due to attention projection matrices)

### Training Configuration
| Parameter | Value |
|-----------|-------|
| Loss | SI-SNR with PIT |
| Optimizer | Adam (lr=1e-3, wd=1e-5) |
| LR Scheduler | ReduceLROnPlateau (×0.5, patience=3) |
| Grad Clip | 5.0 |
| Max Epochs | 20 |
| Early Stop | patience=5 |
| Batch Size | 4 |

### Key Difference vs Original SkiM
| Component | SkiM | SkiMAttention |
|-----------|------|---------------|
| Segment processing | SegLSTM | SegLSTM (same) |
| Memory processing | MemLSTM (LSTM over states) | MemAttention (MHA + FFN + LN) |
| Memory parameter | `hidden_size` | `hidden_size`, `num_heads=8` |
| Streaming memory | LSTM hidden state | Self-attention (no past context in streaming) |

### Expected Performance
- **SI-SNRi**: 10–18 dB (comparable or better than SkiM baseline)
- **SDRi**: 10–20 dB
- Attention-based memory may capture longer-range inter-segment dependencies compared to recurrent MemLSTM

### Files Saved (in `/content/checkpoints_attention/`)
- `best_model_attention.pth` — best checkpoint (lowest validation loss)
- `checkpoint_epoch_*_attention.pth` — periodic checkpoints every 10 epochs
- `final_model_indonesian_skim_attention_raw.pth` — final model with full metadata
- `training_curves_attention.png` — train/val loss & SI-SNR curves
- `separation_demo_*_attention.png` — sample waveform visualization
"""