# -*- coding: utf-8 -*-
"""skim_titml_2mix_raw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXNAcxc61mrE0QEVWWXktWKWHtOPU1cU

# Train SkiM Model from Scratch for Indonesian Speech Separation

**Goal**: Build and train SkiM (Skipping Memory) model from random initialization on TITML-IDN-mix dataset

**Dataset**:
- Train: 3000 mixtures (~3.3 hours)
- Dev: 500 mixtures (~33 minutes)
- Test: 500 mixtures (~33 minutes)
- Format: 16kHz, 2-speaker separation, 4s duration
- Language: Bahasa Indonesia

**Model**: ESPnet SkiM - Small Causal variant
- Architecture: Conv Encoder → SkiM Separator (3 layers, 512 units) → Conv Decoder
- Initialization: Random (no pre-trained weights)
- Loss: SI-SNR with Permutation Invariant Training (PIT)

**Platform**: Google Colab (Free GPU/TPU)

**Differences from Transfer Learning**:
- ✅ No pre-trained weights (train from scratch)
- ✅ Higher learning rate (1e-3 vs 1e-4)
- ✅ Longer training (~30-50 epochs vs 24)
- ✅ Learns Indonesian-specific features directly

## 1. Environment Setup
"""

# Check GPU availability
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
else:
    print("⚠️ No GPU detected! Training will be slow on CPU.")

# Install ESPnet and dependencies
!pip install -q espnet==202304
!pip install -q espnet_model_zoo
!pip install -q soundfile librosa pesq pystoi mir_eval
print("✓ Installation complete!")

# Mount Google Drive (if dataset is stored there)
from google.colab import drive
drive.mount('/content/drive')

# Import required libraries
import os
import json
import numpy as np
import soundfile as sf
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings('ignore')

print("✓ Libraries imported successfully")

"""## 2. Dataset Configuration"""

# Dataset path configuration
# ⚠️ UPDATE THIS PATH based on where you upload your dataset in Colab
DATASET_BASE = "/content/drive/MyDrive/Tugas Akhir/Dataset/IndonesianMix/"

TRAIN_DIR = os.path.join(DATASET_BASE, "train")
DEV_DIR = os.path.join(DATASET_BASE, "dev")
TEST_DIR = os.path.join(DATASET_BASE, "test")

# Verify dataset exists
if os.path.exists(DATASET_BASE):
    print(f"✓ Dataset found at: {DATASET_BASE}")
    print(f"  - Train: {os.path.exists(TRAIN_DIR)}")
    print(f"  - Dev: {os.path.exists(DEV_DIR)}")
    print(f"  - Test: {os.path.exists(TEST_DIR)}")
else:
    print(f"⚠️ Dataset not found at: {DATASET_BASE}")
    print("Please update DATASET_BASE path or upload the dataset!")

# Custom Dataset class for IndonesianMix
class IndonesianMixDataset(Dataset):
    """
    Dataset for TITML-IDN-mix Indonesian speech separation

    Structure:
    - mix/: mixed audio files
    - s1/: source 1 (speaker 1)
    - s2/: source 2 (speaker 2)
    - metadata.json: dataset metadata
    """

    def __init__(self, data_dir, split='train', sample_rate=16000, max_length=64000):
        self.data_dir = Path(data_dir)
        self.split = split
        self.sample_rate = sample_rate
        self.max_length = max_length  # Fixed length (4 seconds at 16kHz)

        # Load metadata
        metadata_path = self.data_dir / 'metadata.json'
        with open(metadata_path, 'r') as f:
            self.metadata = json.load(f)

        # Get file list
        mix_dir = self.data_dir / 'mix'
        self.file_list = sorted([f.stem for f in mix_dir.glob('*.wav')])

        print(f"Loaded {split} split: {len(self.file_list)} samples")
        print(f"Fixed length: {max_length} samples ({max_length/sample_rate:.1f}s)")

    def __len__(self):
        return len(self.file_list)

    def _pad_or_truncate(self, audio):
        """Pad or truncate audio to fixed length"""
        if len(audio) > self.max_length:
            # Truncate
            audio = audio[:self.max_length]
        elif len(audio) < self.max_length:
            # Pad with zeros
            padding = self.max_length - len(audio)
            audio = np.pad(audio, (0, padding), mode='constant')
        return audio

    def __getitem__(self, idx):
        file_id = self.file_list[idx]

        # Load audio files
        mix_path = self.data_dir / 'mix' / f'{file_id}.wav'
        s1_path = self.data_dir / 's1' / f'{file_id}.wav'
        s2_path = self.data_dir / 's2' / f'{file_id}.wav'

        mix, sr_mix = sf.read(mix_path)
        s1, sr_s1 = sf.read(s1_path)
        s2, sr_s2 = sf.read(s2_path)

        # Ensure consistent sample rate
        assert sr_mix == self.sample_rate, f"Expected {self.sample_rate}Hz, got {sr_mix}Hz"

        # Pad or truncate to fixed length
        mix = self._pad_or_truncate(mix)
        s1 = self._pad_or_truncate(s1)
        s2 = self._pad_or_truncate(s2)

        # Convert to torch tensors
        mix_tensor = torch.FloatTensor(mix)
        s1_tensor = torch.FloatTensor(s1)
        s2_tensor = torch.FloatTensor(s2)

        return {
            'mix': mix_tensor,
            's1': s1_tensor,
            's2': s2_tensor,
            'file_id': file_id
        }

print("✓ Dataset class defined")

# Create datasets and dataloaders
BATCH_SIZE = 4  # Adjust based on GPU memory (4-8 for Colab)
NUM_WORKERS = 0  # Set to 0 for Colab stability

train_dataset = IndonesianMixDataset(TRAIN_DIR, split='train')
dev_dataset = IndonesianMixDataset(DEV_DIR, split='dev')
test_dataset = IndonesianMixDataset(TEST_DIR, split='test')

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

dev_loader = DataLoader(
    dev_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print(f"\n✓ DataLoaders created:")
print(f"  - Train batches: {len(train_loader)} (batch_size={BATCH_SIZE})")
print(f"  - Dev batches: {len(dev_loader)}")
print(f"  - Test batches: {len(test_loader)}")

# Verify data loading with a sample batch
sample_batch = next(iter(train_loader))
print(f"\n✓ Sample batch loaded:")
print(f"  - Mix shape: {sample_batch['mix'].shape}")
print(f"  - S1 shape: {sample_batch['s1'].shape}")
print(f"  - S2 shape: {sample_batch['s2'].shape}")
print(f"  - File IDs: {sample_batch['file_id'][:2]}")

"""## 3. Build SkiM Model from Scratch"""

# Import ESPnet components
from espnet2.enh.encoder.conv_encoder import ConvEncoder
from espnet2.enh.decoder.conv_decoder import ConvDecoder
from espnet2.enh.separator.skim_separator import SkiMSeparator
from espnet2.enh.espnet_model import ESPnetEnhancementModel
from espnet2.enh.loss.criterions.tf_domain import FrequencyDomainL1
from espnet2.enh.loss.criterions.time_domain import SISNRLoss
from espnet2.enh.loss.wrappers.pit_solver import PITSolver

print("✓ ESPnet components imported")

# Model configuration - Small Causal variant
model_config = {
    # Encoder/Decoder (TasNet-style for 16kHz)
    'encoder': {
        'channel': 512,        # Number of filters (basis functions)
        'kernel_size': 32,     # 20ms window at 16kHz (32/16000 = 2ms, typically use 16-32)
        'stride': 16,          # 10ms hop (50% overlap)
    },

    'decoder': {
        'channel': 512,        # Must match encoder
        'kernel_size': 32,
        'stride': 16,
    },

    # SkiM Separator - Small Causal
    'separator': {
        'input_dim': 512,      # Must match encoder channel
        'causal': True,        # Causal (online) processing
        'num_spk': 2,          # 2 speakers
        'predict_noise': False,
        'nonlinear': 'relu',   # Activation function
        'layer': 3,            # 3 SkiM blocks (Small variant)
        'unit': 512,           # Hidden LSTM dimension
        'segment_size': 20,    # Segment size for SegLSTM
        'dropout': 0.0,        # Dropout rate
        'mem_type': 'hc',      # Memory type: hidden + cell state
        'seg_overlap': False,  # No overlap for causal mode
    },

    # Model wrapper
    'model': {
        'num_spk': 2,
        'loss_type': 'si_snr',  # Scale-Invariant SNR loss
    }
}

print("✓ Model configuration:")
print(f"  - Architecture: Conv Encoder → SkiM Separator → Conv Decoder")
print(f"  - Variant: Small-Causal (3 layers, 512 units)")
print(f"  - Sample rate: 16 kHz (kernel_size={model_config['encoder']['kernel_size']})")
print(f"  - Loss: SI-SNR with PIT")
print(f"  - Speakers: {model_config['separator']['num_spk']}")

# Build encoder
encoder = ConvEncoder(
    channel=model_config['encoder']['channel'],
    kernel_size=model_config['encoder']['kernel_size'],
    stride=model_config['encoder']['stride'],
)

print("✓ Encoder built:")
print(f"  - Type: Conv1D")
print(f"  - Channels: {model_config['encoder']['channel']}")
print(f"  - Kernel: {model_config['encoder']['kernel_size']} (stride={model_config['encoder']['stride']})")
print(f"  - Input: [batch, time] → Output: [batch, channels, frames]")

# Build separator
separator = SkiMSeparator(
    input_dim=model_config['separator']['input_dim'],
    causal=model_config['separator']['causal'],
    num_spk=model_config['separator']['num_spk'],
    predict_noise=model_config['separator']['predict_noise'],
    nonlinear=model_config['separator']['nonlinear'],
    layer=model_config['separator']['layer'],
    unit=model_config['separator']['unit'],
    segment_size=model_config['separator']['segment_size'],
    dropout=model_config['separator']['dropout'],
    mem_type=model_config['separator']['mem_type'],
    seg_overlap=model_config['separator']['seg_overlap'],
)

print("✓ Separator built:")
print(f"  - Type: SkiM (Skipping Memory)")
print(f"  - Layers: {model_config['separator']['layer']}")
print(f"  - Hidden units: {model_config['separator']['unit']}")
print(f"  - Segment size: {model_config['separator']['segment_size']}")
print(f"  - Causal: {model_config['separator']['causal']}")
print(f"  - Memory type: {model_config['separator']['mem_type']}")
print(f"  - Input: [batch, channels, frames] → Output: [batch, num_spk, channels, frames]")

# Build decoder
decoder = ConvDecoder(
    channel=model_config['decoder']['channel'],
    kernel_size=model_config['decoder']['kernel_size'],
    stride=model_config['decoder']['stride'],
)

print("✓ Decoder built:")
print(f"  - Type: ConvTranspose1D")
print(f"  - Channels: {model_config['decoder']['channel']}")
print(f"  - Kernel: {model_config['decoder']['kernel_size']} (stride={model_config['decoder']['stride']})")
print(f"  - Input: [batch, num_spk, channels, frames] → Output: [batch, num_spk, time]")

# Create loss wrapper with PIT and SI-SNR
si_snr_criterion = SISNRLoss()
pit_wrapper = PITSolver(criterion=si_snr_criterion)

# Wrap in ESPnet Enhancement Model
model = ESPnetEnhancementModel(
    encoder=encoder,
    separator=separator,
    decoder=decoder,
    mask_module=None,  # No additional masking module
    loss_wrappers=[pit_wrapper],  # PIT wrapper with SI-SNR loss
    loss_type='si_snr',  # SI-SNR loss type
)

print("\n✓ Complete model assembled:")
print(f"  - Pipeline: Encoder → Separator → Decoder")
print(f"  - Loss: SI-SNR with PIT (Permutation Invariant Training)")
print(f"  - Initialization: Random weights (from scratch)")

# Count parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nModel Parameters:")
print(f"  - Total: {total_params:,}")
print(f"  - Trainable: {trainable_params:,}")
print(f"  - Estimated GPU memory: ~{total_params * 4 / 1e9:.2f} GB (float32)")

"""## 4. Training Configuration"""

# Training hyperparameters
LEARNING_RATE = 1e-3       # Higher LR for from-scratch (vs 1e-4 for fine-tuning)
NUM_EPOCHS = 20            # Train longer for from-scratch
GRADIENT_CLIP = 5.0        # Gradient clipping threshold
PATIENCE = 5               # Early stopping patience (reduced from 10)
WEIGHT_DECAY = 1e-5        # L2 regularization
CHECKPOINT_DIR = "/content/checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Move model to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
print(f"✓ Model moved to {device}")

# Optimizer - Adam with weight decay
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE,
    betas=(0.9, 0.999),
    eps=1e-8,
    weight_decay=WEIGHT_DECAY
)

# Learning rate scheduler - ReduceLROnPlateau
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',      # Minimize validation loss
    factor=0.5,      # Reduce LR by half
    patience=3       # Wait 3 epochs before reducing
)

print(f"\nTraining Configuration:")
print(f"  - Learning Rate: {LEARNING_RATE} (from-scratch rate)")
print(f"  - Weight Decay: {WEIGHT_DECAY}")
print(f"  - Max Epochs: {NUM_EPOCHS}")
print(f"  - Batch Size: {BATCH_SIZE}")
print(f"  - Gradient Clipping: {GRADIENT_CLIP}")
print(f"  - Early Stopping Patience: {PATIENCE}")
print(f"  - LR Scheduler: ReduceLROnPlateau (factor=0.5, patience=3)")
print(f"  - Checkpoint dir: {CHECKPOINT_DIR}")

"""## 5. Training & Validation Functions"""

# Training function
def train_epoch(model, train_loader, optimizer, device, epoch):
    model.train()
    total_loss = 0
    num_batches = len(train_loader)

    pbar = tqdm(train_loader, desc=f'Epoch {epoch} [Train]')
    for batch_idx, batch in enumerate(pbar):
        # Move to device
        mix = batch['mix'].to(device)  # [batch, time]
        s1 = batch['s1'].to(device)    # [batch, time]
        s2 = batch['s2'].to(device)    # [batch, time]

        # Prepare inputs for ESPnet model
        batch_size = mix.size(0)
        mix_lengths = torch.full((batch_size,), mix.size(1), dtype=torch.long, device=device)

        # ESPnet expects 2D input [batch, time] - encoder adds channel dimension internally
        speech_ref1 = s1  # [batch, time]
        speech_ref2 = s2  # [batch, time]
        ref_lengths = mix_lengths.clone()

        # Forward pass - ESPnet model computes loss internally with PIT
        loss, stats, weight = model(
            speech_mix=mix,
            speech_mix_lengths=mix_lengths,
            speech_ref1=speech_ref1,
            speech_ref1_lengths=ref_lengths,
            speech_ref2=speech_ref2,
            speech_ref2_lengths=ref_lengths
        )

        # Backward pass
        optimizer.zero_grad()
        loss.backward()

        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRADIENT_CLIP)

        optimizer.step()

        # Accumulate loss
        total_loss += loss.item()

        # Update progress bar
        pbar.set_postfix({'loss': f'{loss.item():.4f}'})

    avg_loss = total_loss / num_batches
    return avg_loss

print("✓ Training function defined")

# Validation function
def validate(model, val_loader, device, epoch):
    model.eval()
    total_loss = 0
    num_batches = len(val_loader)

    with torch.no_grad():
        pbar = tqdm(val_loader, desc=f'Epoch {epoch} [Val]')
        for batch in pbar:
            # Move to device
            mix = batch['mix'].to(device)
            s1 = batch['s1'].to(device)
            s2 = batch['s2'].to(device)

            # Prepare inputs
            batch_size = mix.size(0)
            mix_lengths = torch.full((batch_size,), mix.size(1), dtype=torch.long, device=device)

            speech_ref1 = s1  # [batch, time]
            speech_ref2 = s2  # [batch, time]
            ref_lengths = mix_lengths.clone()

            # Forward pass
            loss, stats, weight = model(
                speech_mix=mix,
                speech_mix_lengths=mix_lengths,
                speech_ref1=speech_ref1,
                speech_ref1_lengths=ref_lengths,
                speech_ref2=speech_ref2,
                speech_ref2_lengths=ref_lengths
            )

            total_loss += loss.item()

            pbar.set_postfix({'val_loss': f'{loss.item():.4f}'})

    avg_loss = total_loss / num_batches
    return avg_loss

print("✓ Validation function defined")

"""## 6. Main Training Loop"""

# Main training loop with early stopping
best_val_loss = float('inf')
patience_counter = 0
train_losses = []
val_losses = []

print("=" * 60)
print("Starting Training from Scratch")
print("=" * 60)
print(f"Model: SkiM Small-Causal (3 layers, 512 units)")
print(f"Dataset: TITML-IDN-mix (Indonesian, 16kHz)")
print(f"Training samples: {len(train_dataset)}")
print(f"Validation samples: {len(dev_dataset)}")
print(f"Estimated time: ~{NUM_EPOCHS * len(train_loader) * 0.15 / 60:.1f} minutes ({NUM_EPOCHS} epochs)")
print("=" * 60)

for epoch in range(1, NUM_EPOCHS + 1):
    print(f"\nEpoch {epoch}/{NUM_EPOCHS}")
    print("-" * 60)

    # Train
    train_loss = train_epoch(model, train_loader, optimizer, device, epoch)
    train_losses.append(train_loss)

    # Validate
    val_loss = validate(model, dev_loader, device, epoch)
    val_losses.append(val_loss)

    # Learning rate scheduling
    scheduler.step(val_loss)

    # Print epoch summary
    current_lr = optimizer.param_groups[0]['lr']
    print(f"\nEpoch {epoch} Summary:")
    print(f"  Train Loss: {train_loss:.4f} (SI-SNR: {-train_loss:.2f} dB)")
    print(f"  Val Loss:   {val_loss:.4f} (SI-SNR: {-val_loss:.2f} dB)")
    print(f"  LR:         {current_lr:.6f}")

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_counter = 0

        checkpoint_path = os.path.join(CHECKPOINT_DIR, 'best_model.pth')
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss': train_loss,
            'val_loss': val_loss,
            'best_val_loss': best_val_loss,
            'config': model_config,
        }, checkpoint_path)
        print(f"  ✓ Best model saved! (Val Loss: {val_loss:.4f})")
    else:
        patience_counter += 1
        print(f"  No improvement ({patience_counter}/{PATIENCE})")

    # Early stopping
    if patience_counter >= PATIENCE:
        print(f"\n⚠️ Early stopping triggered after {epoch} epochs")
        print(f"Best validation loss: {best_val_loss:.4f} (SI-SNR: {-best_val_loss:.2f} dB)")
        break

    # Save checkpoint every 10 epochs
    if epoch % 10 == 0:
        checkpoint_path = os.path.join(CHECKPOINT_DIR, f'checkpoint_epoch_{epoch}.pth')
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss': train_loss,
            'val_loss': val_loss,
        }, checkpoint_path)
        print(f"  ✓ Checkpoint saved: epoch_{epoch}.pth")

print("\n" + "=" * 60)
print("Training Complete!")
print("=" * 60)
print(f"Best validation SI-SNR: {-best_val_loss:.2f} dB")

# Plot training curves
plt.figure(figsize=(12, 5))

# Loss curves (negative values)
plt.subplot(1, 2, 1)
plt.plot(train_losses, label='Train Loss', marker='o', markersize=3)
plt.plot(val_losses, label='Val Loss', marker='s', markersize=3)
plt.xlabel('Epoch')
plt.ylabel('Loss (Negative SI-SNR)')
plt.title('Training and Validation Loss')
plt.legend()
plt.grid(True, alpha=0.3)

# SI-SNR curves (positive values for readability)
plt.subplot(1, 2, 2)
plt.plot([-l for l in train_losses], label='Train SI-SNR', marker='o', markersize=3)
plt.plot([-l for l in val_losses], label='Val SI-SNR', marker='s', markersize=3)
plt.xlabel('Epoch')
plt.ylabel('SI-SNR (dB)')
plt.title('Training and Validation SI-SNR')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(CHECKPOINT_DIR, 'training_curves.png'), dpi=150)
plt.show()

print(f"Best validation SI-SNR: {-best_val_loss:.2f} dB")

"""## 7. Evaluation on Test Set"""

# Load best model for evaluation
checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, 'best_model.pth'))
model.load_state_dict(checkpoint['model_state_dict'])
print(f"✓ Best model loaded (Epoch {checkpoint['epoch']}, Val Loss: {checkpoint['val_loss']:.4f})")

# SI-SNR loss function (for PIT)
def si_snr_loss(estimate, target, eps=1e-8):
    """Compute SI-SNR loss (negative SI-SNR for minimization)"""
    # Zero-mean normalization
    estimate = estimate - estimate.mean(dim=-1, keepdim=True)
    target = target - target.mean(dim=-1, keepdim=True)

    # Compute SI-SNR
    s_target = (torch.sum(estimate * target, dim=-1, keepdim=True) * target) / \
               (torch.sum(target ** 2, dim=-1, keepdim=True) + eps)
    e_noise = estimate - s_target

    si_snr = 10 * torch.log10(
        (torch.sum(s_target ** 2, dim=-1) + eps) /
        (torch.sum(e_noise ** 2, dim=-1) + eps)
    )

    return -si_snr.mean()  # Negative for loss

# SI-SNR metric calculation (positive value for evaluation)
def calculate_si_snr(estimate, target, eps=1e-8):
    """Calculate SI-SNR metric (positive value)"""
    estimate = estimate - estimate.mean(dim=-1, keepdim=True)
    target = target - target.mean(dim=-1, keepdim=True)

    s_target = (torch.sum(estimate * target, dim=-1, keepdim=True) * target) / \
               (torch.sum(target ** 2, dim=-1, keepdim=True) + eps)
    e_noise = estimate - s_target

    si_snr = 10 * torch.log10(
        (torch.sum(s_target ** 2, dim=-1) + eps) /
        (torch.sum(e_noise ** 2, dim=-1) + eps)
    )

    return si_snr

# SDR metric calculation (using mir_eval library)
try:
    from mir_eval.separation import bss_eval_sources
    COMPUTE_SDR = True
except ImportError:
    print("⚠️ mir_eval not available, SDR will not be computed")
    COMPUTE_SDR = False

print("✓ Evaluation metrics ready")

# Evaluate on test set
def evaluate_test_set(model, test_loader, device):
    model.eval()

    all_si_snr_mix = []
    all_si_snr_est = []
    all_si_snr_improve = []

    all_sdr_mix = [] if COMPUTE_SDR else None
    all_sdr_est = [] if COMPUTE_SDR else None

    with torch.no_grad():
        pbar = tqdm(test_loader, desc='Evaluating Test Set')
        for batch in pbar:
            mix = batch['mix'].to(device)
            s1 = batch['s1'].to(device)
            s2 = batch['s2'].to(device)

            targets = torch.stack([s1, s2], dim=1)

            # Inference mode - use forward_enhance (no reference signals needed)
            mix_lengths = torch.full((mix.size(0),), mix.size(1), dtype=torch.long, device=device)

            # forward_enhance can return: tuple, list, or tensor
            separated_output = model.forward_enhance(mix, mix_lengths)

            # Handle different return types
            if isinstance(separated_output, (tuple, list)):
                estimates = separated_output[0]
            else:
                estimates = separated_output

            # If still a list/tuple, convert to tensor
            if isinstance(estimates, (list, tuple)):
                estimates = torch.stack(list(estimates), dim=1)

            # Handle potential extra dimensions
            while estimates.dim() > 3:
                estimates = estimates.squeeze(2)

            # Find best permutation using PIT
            perm_losses = []
            for perm in [(0, 1), (1, 0)]:
                loss = 0
                for i, j in enumerate(perm):
                    loss += si_snr_loss(estimates[:, i], targets[:, j])
                perm_losses.append(loss)

            best_perm_idx = torch.argmin(torch.stack(perm_losses))
            best_perm = [(0, 1), (1, 0)][best_perm_idx]

            # Calculate metrics for each sample in batch
            for b in range(mix.size(0)):
                # SI-SNR for mixture (baseline)
                si_snr_mix_s1 = calculate_si_snr(mix[b:b+1], s1[b:b+1])
                si_snr_mix_s2 = calculate_si_snr(mix[b:b+1], s2[b:b+1])
                si_snr_mix = (si_snr_mix_s1 + si_snr_mix_s2) / 2
                all_si_snr_mix.append(si_snr_mix.item())

                # SI-SNR for estimates
                est_s1 = estimates[b:b+1, best_perm[0]]
                est_s2 = estimates[b:b+1, best_perm[1]]
                si_snr_est_s1 = calculate_si_snr(est_s1, s1[b:b+1])
                si_snr_est_s2 = calculate_si_snr(est_s2, s2[b:b+1])
                si_snr_est = (si_snr_est_s1 + si_snr_est_s2) / 2
                all_si_snr_est.append(si_snr_est.item())

                # SI-SNR improvement
                si_snr_improve = si_snr_est - si_snr_mix
                all_si_snr_improve.append(si_snr_improve.item())

                # SDR (optional)
                if COMPUTE_SDR:
                    targets_np = torch.stack([s1[b], s2[b]]).cpu().numpy()
                    mix_np = np.stack([mix[b].cpu().numpy(), mix[b].cpu().numpy()])
                    est_np = torch.stack([est_s1[0], est_s2[0]]).cpu().numpy()

                    sdr_mix, _, _, _ = bss_eval_sources(targets_np, mix_np, compute_permutation=False)
                    sdr_est, _, _, _ = bss_eval_sources(targets_np, est_np, compute_permutation=False)

                    all_sdr_mix.append(sdr_mix.mean())
                    all_sdr_est.append(sdr_est.mean())

    # Compute average metrics
    results = {
        'SI-SNR_mix': np.mean(all_si_snr_mix),
        'SI-SNR_est': np.mean(all_si_snr_est),
        'SI-SNRi': np.mean(all_si_snr_improve),
    }

    if COMPUTE_SDR:
        results['SDR_mix'] = np.mean(all_sdr_mix)
        results['SDR_est'] = np.mean(all_sdr_est)
        results['SDRi'] = np.mean(all_sdr_est) - np.mean(all_sdr_mix)

    return results

# Run evaluation
print("\nEvaluating on test set...")
test_results = evaluate_test_set(model, test_loader, device)

print("\n" + "=" * 60)
print("TEST SET RESULTS (From-Scratch Training)")
print("=" * 60)
for metric, value in test_results.items():
    print(f"{metric:15s}: {value:7.2f} dB")
print("=" * 60)

"""## 8. Demo Visualization"""

# Visualize separation results on a test sample
import IPython.display as ipd

# Get a random test sample
sample_idx = np.random.randint(0, len(test_dataset))
sample = test_dataset[sample_idx]

mix = sample['mix'].unsqueeze(0).to(device)  # [1, time]
s1_true = sample['s1'].cpu().numpy()
s2_true = sample['s2'].cpu().numpy()
file_id = sample['file_id']

print(f"Sample: {file_id}")

# Perform separation
model.eval()
with torch.no_grad():
    mix_lengths = torch.tensor([mix.size(1)], dtype=torch.long, device=device)

    # Use forward_enhance for inference (no reference signals)
    separated_output = model.forward_enhance(mix, mix_lengths)

    # Handle different return types
    if isinstance(separated_output, (tuple, list)):
        estimates = separated_output[0]
    else:
        estimates = separated_output

    # If still a list/tuple, stack it
    if isinstance(estimates, (list, tuple)):
        estimates = torch.stack(list(estimates), dim=1)

    # Handle extra dimensions if present
    while estimates.dim() > 3:
        estimates = estimates.squeeze(2)

# Fix permutation problem: Find which permutation matches ground truth best
s1_true_tensor = torch.FloatTensor(s1_true).unsqueeze(0).to(device)
s2_true_tensor = torch.FloatTensor(s2_true).unsqueeze(0).to(device)

# Compute loss for both permutations
perm1_loss = si_snr_loss(estimates[0:1, 0], s1_true_tensor) + si_snr_loss(estimates[0:1, 1], s2_true_tensor)
perm2_loss = si_snr_loss(estimates[0:1, 0], s2_true_tensor) + si_snr_loss(estimates[0:1, 1], s1_true_tensor)

# Select best permutation
if perm2_loss < perm1_loss:
    # Swap: est[0]→s2, est[1]→s1
    s1_est = estimates[0, 1].cpu().numpy()
    s2_est = estimates[0, 0].cpu().numpy()
    print("⚠️ Permutation swapped (this is normal - model doesn't know speaker identity)")
else:
    # Original order: est[0]→s1, est[1]→s2
    s1_est = estimates[0, 0].cpu().numpy()
    s2_est = estimates[0, 1].cpu().numpy()

mix_np = mix[0].cpu().numpy()

# Calculate SI-SNR for this sample (now with correct permutation)
si_snr_s1 = calculate_si_snr(
    torch.FloatTensor(s1_est).unsqueeze(0),
    torch.FloatTensor(s1_true).unsqueeze(0)
).item()
si_snr_s2 = calculate_si_snr(
    torch.FloatTensor(s2_est).unsqueeze(0),
    torch.FloatTensor(s2_true).unsqueeze(0)
).item()

print(f"\nSeparation Quality:")
print(f"  SI-SNR Speaker 1: {si_snr_s1:.2f} dB")
print(f"  SI-SNR Speaker 2: {si_snr_s2:.2f} dB")
print(f"  Average SI-SNR:   {(si_snr_s1 + si_snr_s2) / 2:.2f} dB")

# Visualize waveforms
fig, axes = plt.subplots(5, 1, figsize=(15, 10))

time_axis = np.arange(len(mix_np)) / 16000  # 16kHz sample rate

axes[0].plot(time_axis, mix_np, color='black', linewidth=0.5)
axes[0].set_title('Mixed Audio (Input)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Amplitude')
axes[0].grid(True, alpha=0.3)

axes[1].plot(time_axis, s1_true, color='blue', linewidth=0.5)
axes[1].set_title('Speaker 1 - Ground Truth', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Amplitude')
axes[1].grid(True, alpha=0.3)

axes[2].plot(time_axis, s1_est, color='cyan', linewidth=0.5)
axes[2].set_title(f'Speaker 1 - Estimated (SI-SNR: {si_snr_s1:.2f} dB)', fontsize=12, fontweight='bold')
axes[2].set_ylabel('Amplitude')
axes[2].grid(True, alpha=0.3)

axes[3].plot(time_axis, s2_true, color='red', linewidth=0.5)
axes[3].set_title('Speaker 2 - Ground Truth', fontsize=12, fontweight='bold')
axes[3].set_ylabel('Amplitude')
axes[3].grid(True, alpha=0.3)

axes[4].plot(time_axis, s2_est, color='orange', linewidth=0.5)
axes[4].set_title(f'Speaker 2 - Estimated (SI-SNR: {si_snr_s2:.2f} dB)', fontsize=12, fontweight='bold')
axes[4].set_ylabel('Amplitude')
axes[4].set_xlabel('Time (s)')
axes[4].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(CHECKPOINT_DIR, f'separation_demo_{file_id}.png'), dpi=150)
plt.show()

# Play audio samples (for Colab)
print("🔊 Audio Playback:\n")

print("Mixed Audio:")
ipd.display(ipd.Audio(mix_np, rate=16000))

print("\nSpeaker 1 - Ground Truth:")
ipd.display(ipd.Audio(s1_true, rate=16000))

print("Speaker 1 - Estimated:")
ipd.display(ipd.Audio(s1_est, rate=16000))

print("\nSpeaker 2 - Ground Truth:")
ipd.display(ipd.Audio(s2_true, rate=16000))

print("Speaker 2 - Estimated:")
ipd.display(ipd.Audio(s2_est, rate=16000))

"""## 9. Save Final Model"""

# Save final model with complete information
final_model_path = os.path.join(CHECKPOINT_DIR, 'final_model_indonesian_skim_raw.pth')

torch.save({
    'model_state_dict': model.state_dict(),
    'config': model_config,
    'test_results': test_results,
    'train_losses': train_losses,
    'val_losses': val_losses,
    'best_val_loss': best_val_loss,
    'hyperparameters': {
        'learning_rate': LEARNING_RATE,
        'batch_size': BATCH_SIZE,
        'num_epochs': NUM_EPOCHS,
        'gradient_clip': GRADIENT_CLIP,
        'weight_decay': WEIGHT_DECAY,
        'patience': PATIENCE,
        'training_type': 'from_scratch',
    },
    'dataset_info': {
        'name': 'TITML-IDN-mix',
        'sample_rate': 16000,
        'train_samples': len(train_dataset),
        'dev_samples': len(dev_dataset),
        'test_samples': len(test_dataset),
    }
}, final_model_path)

print(f"✓ Final model saved to: {final_model_path}")
print(f"\nModel can be loaded with:")
print(f"  checkpoint = torch.load('{final_model_path}')")
print(f"  model.load_state_dict(checkpoint['model_state_dict'])")

"""---

## Summary

### Training Configuration
- **Model**: SkiM Small-Causal (3 layers, 512 units)
- **Training Type**: From Scratch (random initialization)
- **Dataset**: TITML-IDN-mix (Indonesian, 16kHz)
- **Training Samples**: 3000
- **Loss Function**: SI-SNR with PIT
- **Learning Rate**: 1e-3 (higher than transfer learning)
- **Epochs Trained**: Variable (early stopping)

### Architecture Details
- **Encoder**: Conv1D (512 channels, kernel=32, stride=16)
- **Separator**: SkiM (3 blocks, 512 hidden units, causal, segment_size=20)
- **Decoder**: ConvTranspose1D (512 channels, kernel=32, stride=16)
- **Total Parameters**: ~17M

### Key Differences from Transfer Learning
| Aspect | Transfer Learning | From Scratch (This Notebook) |
|--------|------------------|-----------------------------|
| **Initialization** | Pre-trained (WSJ0-2mix) | Random weights |
| **Learning Rate** | 1e-4 | 1e-3 |
| **Training Time** | ~4-6 hours (24 epochs) | ~6-12 hours (30-50 epochs) |
| **Domain Bias** | English speech patterns | Indonesian-only |
| **Convergence** | Faster | Slower but potentially better |

### Expected Performance
- **SI-SNRi (Improvement)**: 10-18 dB (vs 8.34 dB transfer learning)
- **SDRi**: 10-20 dB (vs 9.10 dB transfer learning)
- From-scratch models can outperform transfer learning when:
  - Target domain differs significantly from source (Indonesian vs English)
  - Sufficient training data available (3000 samples ✓)
  - Trained for enough epochs

### Next Steps
1. **Compare Results**: Compare test metrics with transfer learning baseline
2. **Hyperparameter Tuning**: Experiment with learning rate, batch size
3. **Architecture Variants**: Try Large-Causal (6 layers) if performance insufficient
4. **Data Augmentation**: Add pitch shift, time stretch for better generalization
5. **Analysis**: Analyze which speakers/conditions work best/worst

### Files Saved
- `best_model.pth`: Best model checkpoint (lowest validation loss)
- `checkpoint_epoch_*.pth`: Periodic checkpoints every 10 epochs
- `final_model_indonesian_skim_raw.pth`: Final model with complete metadata
- `training_curves.png`: Training/validation loss curves
- `separation_demo_*.png`: Sample separation visualization
"""